- hosts:
  - all
  sudo: True
  gather_facts: True
  vars:

  roles:

  tasks:
  - name: Install default packages
    yum: name={{ item }} state=latest
    with_items:
     - vim-enhanced

  handlers:
